jobs:
- job: Test
  strategy:
    maxParallel: 2
    matrix:
      DefaultLocations:
        CustomLocations: false
      CustomLocations:
        CustomLocations: true
  steps:
  - powershell: |
      Get-PackageProvider NuGet -ForceBootstrap

      Install-Module -Name Pester -Force

      $results = Invoke-Pester Tests\Tests.ps1 -PassThru

      if (!($results.FailedCount -eq 0)){
          throw "Tests failed."
      } 

trigger:
- development
